name: _reusable push

on:
  workflow_call:
    inputs:
      oci-name:
        required: true
        type: string

env:
  OCI_FULL_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{ inputs.oci-name }}

jobs:
  push:
    name: ${{ inputs.oci-name }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ inputs.oci-name }}
          path: images

      - name: Load Docker image
        run: docker load --input images/image.tar

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case oci name
        run: |
          echo "OCI_FULL_NAME_LC=${OCI_FULL_NAME,,}" >>${GITHUB_ENV}

      - name: Push Docker image
        run: |
          docker push ${{ env.OCI_FULL_NAME_LC }}:${{ github.run_number }}
          docker push ${{ env.OCI_FULL_NAME_LC }}:latest
