name: Frontend Build and Push

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yaml
    with:
      oci-name: frontend
      context: .
      dockerfile: ./Dockerfile
    permissions:
      packages: write
      contents: read

  push:
    name: Push
    needs: build
    uses: ./.github/workflows/_push.yaml
    with:
      oci-name: frontend
    permissions:
      packages: write
      contents: read