name: Frontend Build and Push

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'next.config.ts'
      - 'tailwind.config.ts'
      - 'postcss.config.mjs'
      - 'tsconfig.json'
      - 'biome.json'
      - '.github/workflows/frontend-build-push.yaml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  build:
    name: Build Frontend
    uses: ./.github/workflows/_build.yaml
    with:
      oci-name: frontend
      context: .
      dockerfile: ./Dockerfile
    permissions:
      packages: write
      contents: read

  push:
    name: Push Frontend
    needs: build
    uses: ./.github/workflows/_push.yaml
    with:
      oci-name: frontend
    permissions:
      packages: write
      contents: read